Repository everyonewaiter/everyone-waiter-fe, pull requests merged in 2025-04, with the labels that each got.

#2 chore: 라이브러리 초기 세팅
  package.json
  pnpm-lock.yaml
  src/app/get-query-client.ts
  src/app/layout.tsx
  src/app/query-providers.tsx
Labels: 📦chore

#3 chore: tailwind config 생성 및 스타일 작성
  src/app/layout.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 📦chore

#5 feat: axios 인스턴스 및 인터셉터 구현
  src/lib/axios/instance.ts
  src/lib/cookies/index.ts
Labels: ✨feat

#7 feat: input 및 폼 관련 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/app/test/page.tsx
  src/components/common/Input.tsx
  src/components/common/form.tsx
  src/components/common/label.tsx
Labels: ✨feat

#6 SKEU-15/login-ui
  .eslintrc.json
  .prettierrc
  package.json
  pnpm-lock.yaml
  public/file.svg
  public/gif/signup-completed.gif
  public/gif/signup-loading.gif
  public/globe.svg
  public/images/hourglass.svg
  public/images/login-cover.svg
  public/images/logo-with-text-white.svg
  public/images/logo-with-text.svg
  public/images/splash.png
  public/logo.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/(splash)/page.tsx
  src/app/auth/email/layout.tsx
  src/app/auth/email/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/completed/page.tsx
  src/app/signup/layout.tsx
  src/app/signup/loading/page.tsx
  src/app/signup/page.tsx
  src/app/test/page.tsx
  src/components/common/Alert/Alert.tsx
  src/components/common/Alert/Components.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/form.tsx
  src/components/common/label.tsx
  src/schema/login.schema.ts
  src/schema/signup.schema.ts
  tsconfig.json
Labels: ✨feat

#13 feat: 레이아웃 구현
  public/images/logo-cloche.svg
  src/app/(main)/_components/MobileHeader.tsx
  src/app/(main)/_components/MobileSidebar.tsx
  src/app/(main)/_components/SideBarButton.tsx
  src/app/(main)/_components/Sidebar.tsx
  src/app/(main)/admin/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/menu/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/form.tsx
Labels: ✨feat

#12 fix: 로그인/회원가입 레이아웃 수정
  src/app/layout.tsx
  src/app/signup/layout.tsx
Labels: 🐛fix

#14 feat: 매장 등록, 매장 현황 UI 구현
  package.json
  pnpm-lock.yaml
  public/gif/hourglass.gif
  public/gif/no-stores.gif
  public/gif/rejected.gif
  public/icons/file-attach.svg
  public/icons/hamburger.svg
  src/app/auth/email/layout.tsx
  src/app/auth/email/page.tsx
  src/app/auth/mail/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/app/store/_components/CreateForm.tsx
  src/app/store/_components/MobileTableItem.tsx
  src/app/store/_components/Row.tsx
  src/app/store/_components/StepIndicator.tsx
  src/app/store/_components/UploadPhoto.tsx
  src/app/store/_components/modals/PendingAcceptModal.tsx
  src/app/store/_components/modals/PhotoForBusiness.tsx
  src/app/store/_components/modals/StoreApplicationModal.tsx
  src/app/store/create/page.tsx
  src/app/stores/page.tsx
  src/components/GuideComponent.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/LabeledInput.tsx
  src/components/common/Pagination/Component.tsx
  src/components/common/Pagination/Paginations.tsx
  src/components/common/ResponsiveButton.tsx
  src/components/common/form.tsx
  src/components/common/label.tsx
  src/components/modal/largeModalLayout.tsx
  src/hooks/use-overlay.ts
  src/hooks/useOpenDaumPostcode.ts
  src/lib/formatting/formatBusinessNumber.tsx
  src/lib/formatting/formatDate.tsx
  src/lib/formatting/formatPhoneNumber.tsx
  src/schema/store.schema.ts
Labels: ✨feat

#15 feat: 매장 등록, 매장 현황 API 연결
  next.config.ts
  src/app/auth/mail/page.tsx
  src/app/globals.css
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/layout.tsx
  src/app/store/_components/CreateForm.tsx
  src/app/store/_components/MobileTableItem.tsx
  src/app/store/_components/Row.tsx
  src/app/store/_components/modals/PendingAcceptModal.tsx
  src/app/store/_components/modals/PhotoForBusiness.tsx
  src/app/store/_components/modals/StoreApplicationModal.tsx
  src/app/store/create/page.tsx
  src/app/stores/page.tsx
  src/components/common/Button.tsx
  src/components/common/Pagination/Component.tsx
  src/components/common/ResponsiveButton.tsx
  src/hooks/useStores.tsx
  src/lib/api/auth.api.ts
  src/lib/api/paths.ts
  src/lib/api/stores.api.ts
  src/lib/axios/instance.ts
  src/lib/formatting/formatPhoneNumber.tsx
  src/schema/store.schema.ts
  src/styles/responsiveButton.tsx
  src/types/store.d.ts
Labels: ✨feat

#17 feat: 매장 정보 페이지 UI
  language=src/app/store/info/page.tsx
  package.json
  pnpm-lock.yaml
  public/icons/edit-contained.svg
  public/icons/people.svg
  public/icons/trash-02.svg
  src/app/(main)/_components/MobileSidebar.tsx
  src/app/(main)/_components/Sidebar.tsx
  src/app/(main)/_components/renderIcons.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/signup/page.tsx
  src/app/store/info/page.tsx
  src/app/subscription/page.tsx
  src/components/SectionHeader.tsx
  src/components/common/ResponsiveButton.tsx
  src/components/icons/index.ts
  src/components/layout/Header.tsx
  src/components/layout/MainLayout.tsx
  src/constants/sidebarMenus.ts
  src/hooks/store/useSidebar.ts
  src/schema/store.schema.ts
  src/types/store.d.ts
Labels: ✨feat

#18 feat: 매장 등록 어드민 페이지 UI 구현
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/app/store/_components/Row.tsx
  src/app/store/info/page.tsx
  src/app/stores/approval/page.tsx
  src/app/stores/page.tsx
  src/components/SectionHeader.tsx
  src/components/Table.tsx
  src/components/common/Form.tsx
  src/components/common/Label.tsx
  src/components/common/LabeledInput.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainLayout.tsx
  src/hooks/store/useAccount.ts
  src/lib/api/auth.api.ts
  src/types/auth.d.ts
Labels: ✨feat
